

/**
 *
 * @author ftoon
 */
public class choose extends javax.swing.JFrame {

    /**
     * Creates new form choose
     */
    public choose() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button1 = new javax.swing.JButton();
        button2 = new javax.swing.JButton();
        button3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("تطبيق غرسة ");
        setLocationByPlatform(true);
        setSize(new java.awt.Dimension(552, 530));
        getContentPane().setLayout(null);

        button1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        button1.setForeground(new java.awt.Color(0, 102, 0));
        button1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ftoon\\OneDrive\\الصور\\زهولر1.jpg")); // NOI18N
        button1.setText("زهور");
        button1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(156, 200, 144)));
        button1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        getContentPane().add(button1);
        button1.setBounds(500, 220, 190, 140);

        button2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        button2.setForeground(new java.awt.Color(0, 102, 0));
        button2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ftoon\\OneDrive\\الصور\\فواكه1.jpg")); // NOI18N
        button2.setText("فواكه");
        button2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(167, 201, 131)));
        button2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        getContentPane().add(button2);
        button2.setBounds(280, 220, 190, 140);

        button3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        button3.setForeground(new java.awt.Color(0, 102, 0));
        button3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ftoon\\OneDrive\\الصور\\خضار1.jpg")); // NOI18N
        button3.setText("خضار");
        button3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(162, 200, 143)));
        button3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        getContentPane().add(button3);
        button3.setBounds(40, 220, 190, 140);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(18, 88, 23));
        jLabel1.setText("ما الذي تريد زراعته؟");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 90, 340, 100);

        backgroundLabel.setFont(new java.awt.Font("Arabic Typesetting", 0, 16)); // NOI18N
        backgroundLabel.setForeground(new java.awt.Color(12, 120, 28));
        backgroundLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\ftoon\\OneDrive\\الصور\\خلفية.jpg")); // NOI18N
        getContentPane().add(backgroundLabel);
        backgroundLabel.setBounds(0, 0, 754, 530);

        setSize(new java.awt.Dimension(774, 586));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        //open  JFrame 3(flowers)
        Flowers frame3 = new Flowers();
        frame3.show();//display frame 3 here
        dispose();//close current frame 2(choose)after open frame 3
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        //open  JFrame 4(fruits)
        Fruits frame4 = new Fruits();
        frame4.show();//display frame 4 here
        dispose();//close current frame 2(choose)after open frame 4
    }//GEN-LAST:event_button2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
        //open  JFrame 5(Vegetables)
        Vegetables frame5 = new Vegetables();
        frame5.show();//display frame 5 here
        dispose();//close current frame 2(choose)after open frame 5
    }//GEN-LAST:event_button3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new choose().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JButton button1;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
